#!/bin/bash

set -e
psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB -w <<-EOSQL
        TABLESPACE pg_default;
        CREATE TABLE IF NOT EXISTS public."Post"
        (
            "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
            "Owner" text COLLATE pg_catalog."default" NOT NULL,
            "Subscript" text COLLATE pg_catalog."default",
            "PhotoForAll" text COLLATE pg_catalog."default" NOT NULL,
            CONSTRAINT "Post_pkey" PRIMARY KEY ("Id")
        )

        ALTER TABLE IF EXISTS public."Post"
            OWNER to $POSTGRES_USER;

        CREATE TABLE IF NOT EXISTS public."User"
        (
            "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "Login" text COLLATE pg_catalog."default" NOT NULL,
            "Password" text COLLATE pg_catalog."default" NOT NULL,
            CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
            CONSTRAINT "User_Login_key" UNIQUE ("Login")
        )

        ALTER TABLE IF EXISTS public."User"
            OWNER to $POSTGRES_USER;
EOSQL