# Generated by Django 4.0 on 2023-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20230325_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproducts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
