# Generated by Django 4.0 on 2023-04-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_options_and_more'),
        ('clients', '0008_alter_clients_options_alter_clients_balance_and_more'),
        ('basket', '0003_alter_basketproducts_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketproducts',
            options={'verbose_name': 'Basket product', 'verbose_name_plural': 'Basket products'},
        ),
        migrations.RemoveField(
            model_name='basketproducts',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='basketproducts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='basketproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Product'),
        ),
    ]
