# Generated by Django 4.0 on 2023-04-09 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clients_status'),
        ('products', '0003_alter_products_id_alter_productscategories_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Products review',
                'verbose_name_plural': 'Products reviews',
            },
        ),
    ]
