# Generated by Django 4.0 on 2023-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='extra_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra info'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
    ]
