# Generated by Django 3.2.18 on 2023-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsCategories',
        ),
    ]
