# Generated by Django 3.2.18 on 2023-04-12 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=3000, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(3000)], verbose_name='Price'),
        ),
    ]
