# Generated by Django 3.2.18 on 2023-04-13 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is premium'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=3000, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(3000)], verbose_name='Price'),
        ),
    ]
