# Generated by Django 3.2.18 on 2023-04-13 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230413_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='asd', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(3000)], verbose_name='Price'),
        ),
    ]
