# Generated by Django 4.1.7 on 2023-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='qwerty', max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
