# Generated by Django 4.0 on 2023-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='login',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='asdasda@qwe.com', max_length=255, unique=True, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
