# Generated by Django 4.0 on 2023-04-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('waiting for payment', 'WAITING_FOR_PAYMENT'), ('processed', 'PROCESSED')], max_length=255, verbose_name='Status'),
        ),
    ]
