# Generated by Django 4.0 on 2023-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('waiting for payment', 'WAITING_FOR_PAYMENT'), ('processed', 'PROCESSED')], default='waiting for payment', max_length=255, verbose_name='Status'),
        ),
    ]
