$script = <<SCRIPT
sudo pacman -Sy archlinux-keyring --noconfirm
sudo pacman -S --noconfirm nano docker git docker-compose virtualbox-guest-utils-nox
echo -e "y\\ny" | sudo pacman -Scc
sudo systemctl enable docker
sudo systemctl start docker
sudo sed -iold 's/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.box_version = "20230401.139781"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.check_guest_additions = true
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.synced_folder "../", "/vagrant"
  config.vm.boot_timeout = 1200
  config.vm.provision "shell", inline: $script
end
