# Generated by Django 4.0 on 2023-04-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clients_status'),
        ('promocodes', '0003_alter_promocodes_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodes',
            options={'verbose_name': 'Promocode', 'verbose_name_plural': 'Promocodes'},
        ),
        migrations.RemoveField(
            model_name='promocodes',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='promocodes',
            name='key',
        ),
        migrations.AddField(
            model_name='promocodes',
            name='code',
            field=models.CharField(default='asd', max_length=255, verbose_name='Промокоды'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PromoCodesActivations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Активация промокодоа',
                'verbose_name_plural': 'Активации промокодов',
            },
        ),
    ]
