# Generated by Django 4.0 on 2023-04-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0005_promocodes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodesactivations',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promocodes.promocodes', verbose_name='Код'),
        ),
    ]
