# Generated by Django 4.0 on 2023-04-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clients_options_alter_clients_balance_and_more'),
        ('promocodes', '0006_alter_promocodesactivations_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodesactivations',
            options={'verbose_name': 'Promocode activation', 'verbose_name_plural': 'Promocode activations'},
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='promocodesactivations',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='promocodesactivations',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promocodes.promocodes', verbose_name='Promocode'),
        ),
    ]
