# Generated by Django 3.2.18 on 2023-04-13 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0007_alter_promocodesactivations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(100)], verbose_name='Amount'),
        ),
    ]
