# Generated by Django 4.0 on 2023-04-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clients_options_alter_clients_balance_and_more'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtokens',
            options={'verbose_name': 'Refresh token', 'verbose_name_plural': 'Refresh tokens'},
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='refreshtokens',
            name='token',
            field=models.CharField(max_length=255, verbose_name='Token'),
        ),
    ]
