# Generated by Django 3.2.18 on 2023-04-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_auto_20230413_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10000, verbose_name='Key')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Secret key',
                'verbose_name_plural': 'Secret keys',
            },
        ),
    ]
