# Generated by Django 3.2.18 on 2023-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretkeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkeys',
            name='key',
            field=models.CharField(max_length=1000, verbose_name='Key'),
        ),
    ]
