# Generated by Django 3.2.18 on 2023-04-14 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('secretkeys', '0003_alter_secretkeys_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkeys',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 9, 4, 20, 706962, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='secretkeys',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
