# Generated by Django 3.2.18 on 2023-04-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secretkeys', '0006_alter_secretkeys_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkeys',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
